name: Act on Release
 
on: [repository_dispatch]
 
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}' for version '${{ github.event.client_payload.version }}'"
      - name: Create Release
        id: create_release
        if: github.event.action == 'release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.client_payload.version }}
          release_name: Release ${{ github.event.client_payload.version }}
          draft: false
          prerelease: false
